name: 'Site Cat LGTM'
description: 'Site-cat appears on issue when someone posts `lgtm`'
inputs:
  token:
    description: 'GitHub Token(scope: repo)'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
