name: Site Cat Test
on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: redshoga/site-cat-action@0.20
        with:
          token: ${{ secrets.LGTM_TOKEN }}
